### PR TITLE
Add Pivx

### PR DESCRIPTION
**Pull request by panleone**
Trying to add integration for PIVX: it is bitcoin based, so more or less I copied the bitcoin coinstack and changed names when needed

### CODE REVIEW

**Comment by panleone** [comment]
Trezor blockbook supports PIVX

**Comment by panleone** [comment]
I also didn't understand precisely how to make circleci config rpc work
    rpc-url: http://user:password@pivx-svc.unchained-dev.svc.cluster.local:8332
    indexer-url: http://pivx-svc.unchained-dev.svc.cluster.local:8001
    indexer-ws-url: ws://pivx-svc.unchained-dev.svc.cluster.local:8001/websocket

**Comment by kaladinlight** [comment]
@panleone the circle configuration uses service routing for our self hosted deployments. The dns would have to be configured as well to expose this coinstack via shapeshift.com. As it costs money for us to host coinstacks, there will need to be some discussion about supporting this chain as it is not currently on our road map.

I would like to thank you for one of the first external coinstack additions however! You should also know that all of the deployment logic exists for you to deploy your own cluster and coinstacks if you wish to provide this coinstack for yourself. Our cluster launcher is set up for aws and we use pulumi for our IAC.

I will give further review when back from holiday. Cheers!

**Comment by DiggyDiggy2** [comment]
gm @panleone. Please enter our Discord, https://discord.gg/shapeshift and find the "partner-request" channel. From there, you can start the process of connecting with the designated DAO representatives and kicking off a discussion about a possible integration.

**Comment by 0xdef1cafe** [comment]
@panleone thanks for the contribution, but adding PIVX chain is not on the DAO roadmap at this stage, and we can't bear the maintenance burden of merging this right now.

you're more than welcome to fork unchained and run your own infrastructure, but we won't be merging and hosting this.

**Pull request closed without merging**
